### ISSUE TITLE
Support ConnectionString as an alternative to InstrumentationKey

### ISSUE THREAD

**Issue by 50Wliu** [IvanJosipovic/BlazorApplicationInsights#129]
App Insights [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string?tabs=net) states "We recommend the use of connection strings over instrumentation keys". It would be nice for this package to support setting connection strings instead of only instrumentation keys :).

**Comment by Izzmo** [comment]
Agreed. This is is a critical need for Sovereign clouds.

**Comment by Izzmo** [comment]
This looks to already be done actually, I recommend closing @50Wliu 

https://github.com/IvanJosipovic/BlazorApplicationInsights/blob/5a8403c7ee33a30f1fd7bbc86a3e70f4300084ed/src/BlazorApplicationInsights.Sample/wwwroot/index.html#L15

**Comment by 50Wliu** [comment]
I'm not so sure - that's an example `instrumentationKey`, _not_ `connectionString`: https://docs.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string?tabs=js#code-samples.

**Comment by 50Wliu** [comment]
Also, I suppose this specific feature request is for a programmatic API to set the connection string. Right now there's only SetInstrumentationKey.

**Comment by IvanJosipovic** [comment]
> Also, I suppose this specific feature request is for a programmatic API to set the connection string. Right now there's only SetInstrumentationKey.

I looked into this briefly in the last update. I added: https://github.com/IvanJosipovic/BlazorApplicationInsights/blob/5a8403c7ee33a30f1fd7bbc86a3e70f4300084ed/src/BlazorApplicationInsights/IApplicationInsights.cs#L182

However, this function needs more work, as it turns out that AppInsights actually splits the connection string and sets a number of internal parameters.

**Comment by 50Wliu** [comment]
Oh interesting, I wasn't aware of the dependency tracking issues. Thanks for letting me know!

**Comment by Grandizer** [comment]
I take it that `SetConnectionString` does not 100% work yet? Based on my attempts to get it to work and getting an error that it could not find `blazorApplicationInsights.setConnectionString`. I even tried to take the source code for the js interop file and put it local (and change the reference to my new file) and no luck. But my local file works fine when I switch to `SetInstrumentationKey`.

**Comment by daver77** [comment]
Does connectionString work now? I can see it has been added to the wiki instead of instrumentationKey

`cfg: {
      connectionString:"InstrumentationKey=00000000-0000-0000-0000-000000000000;",
      disableFetchTracking: false,
      enableCorsCorrelation: true,
      enableRequestHeaderTracking: true,
      enableResponseHeaderTracking: true
  }});`

**Comment by IvanJosipovic** [comment]
> Does connectionString work now? I can see it has been added to the wiki instead of instrumentationKey
> 
> ```
> cfg: {
>       **connectionString**:"InstrumentationKey=00000000-0000-0000-0000-000000000000;",
>       disableFetchTracking: false,
>       enableCorsCorrelation: true,
>       enableRequestHeaderTracking: true,
>       enableResponseHeaderTracking: true
>   }});
> ```
> 
> Also, I noticed in your script you have D=instrumentationKey
> 
> ![image](https://user-images.githubusercontent.com/2369739/165770664-eb8fea97-df7c-4eea-aa5c-20c1c89c7c09.png)
> 
> whereas in the [documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript?tabs=snippet#snippet-based-setup) it shows D=connectionString
> 
> ![image](https://user-images.githubusercontent.com/2369739/165770954-0b24d917-ea8d-4710-bc7a-a838045251e6.png)
> 
> Does that need to be changed?

No, this is not needed. You can use ConnectionString as is. The only gap is around setting it programmatically.

**Comment by IvanJosipovic** [comment]
I'm closing this issue for now, I have documented how to set the ConnectionString Programmatically for a Blazor WASM ASP.NET Core Hosted project. This solution will need to be manually implemented for self hosted Blazor, it essentially uses a cookie to store the ConnectionString.

I do not recommend using SetInstrumentationKey and SetConnectionString (due to #90) and they will likely be marked as obsolete in a future version.
