### ISSUE TITLE
Gracefully handle lack of App Insights (due to adblocker, etc)

### ISSUE THREAD

**Issue by 50Wliu** [IvanJosipovic/BlazorApplicationInsights#130]
Most ad blockers out there block telemetry scripts like AI. This package should gracefully handle the case where App Insights is blocked or otherwise couldn't be loaded and do nothing, rather than throwing (user-visible) errors on every page load, e.g.:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: appInsights is not defined
      ReferenceError: appInsights is not defined
          at Object.setInstrumentationKey (https://localhost:5001/_content/BlazorApplicationInsights/JsInterop.js:71:9)
```

**Comment by IvanJosipovic** [comment]
Hey,
I do have tests for when AI is blocked, https://github.com/IvanJosipovic/BlazorApplicationInsights/blob/967bc2a8decb29fcbbcbc6ebeb06286b803ac282/src/BlazorApplicationInsights.Tests/UnitTests.cs#L546

In my quick testing, running this function with AI blocked doesn't cause any issues. The AI snipped creates the "appInsights" objects and it should be available if AI is blocked.

Are you missing the snipped in the index.html?

**Comment by 50Wliu** [comment]
Ooooh, you're right. No, right now we're actually including the script directly rather than using the snippet because of [#1742](https://github.com/microsoft/ApplicationInsights-JS/issues/1742). Sorry for the false alarm!
