### ISSUE TITLE
Give logger provider a ProviderAlias attribute

### ISSUE THREAD

**Issue by chunliu** [IvanJosipovic/BlazorApplicationInsights#135]
Please add a `ProviderAlias` attribute to the logger provider so that a shorter name can be used in appsettings.json.

**Comment by chunliu** [comment]
If I want to use a different log level for logging default and this logger provider, is there a better way other than using the long name in the appsettings.json? And what's the concern to have the dependency on `Microsoft.Extensions.Logging`? Just curious...

**Comment by IvanJosipovic** [comment]
Provider Alias has been added to v3.
