### ISSUE TITLE
Disable telemetry in Development environment

### ISSUE THREAD

**Issue by sergey-tihon** [IvanJosipovic/BlazorApplicationInsights#142]
Is there an `official` and easy way to disable AppInsights telemetry in Development environment?

**Comment by IvanJosipovic** [comment]
Not that I'm aware of. I keep it on but use a Dev App Insights instance so that alerts don't trigger. Additionally, you could use an adblocker.

**Comment by sergey-tihon** [comment]
Quite from https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript#telemetry-initializers

> The input argument to addTelemetryInitializer is a callback that takes a [ITelemetryItem](https://github.com/microsoft/ApplicationInsights-JS/blob/master/API-reference.md#addTelemetryInitializer) as an argument and returns a `boolean` or `void`. If returning false, the telemetry item isn't sent, else it proceeds to the next telemetry initializer, if any, or is sent to the telemetry collection endpoint.


Looks like [telemetryInitializer](https://github.com/IvanJosipovic/BlazorApplicationInsights/blob/master/src/BlazorApplicationInsights/wwwroot/JsInterop.js#L3) may return `false` and disable telemetry.

We can add property to `TelemetryItem`, for example
```csharp
public bool SendTelemetry {get; set} = true;
```
that control this behaviour during initialisation.

p.s. solution found on [StackOverflow](https://stackoverflow.com/questions/59535524/disable-application-insights-browser-telemetry-for-a-recurring-javascript-call)

**Comment by IvanJosipovic** [comment]
This is now supported in v3.
