### ISSUE TITLE
Feature Request: Get User and Session IDs

### ISSUE THREAD

**Issue by tdashworth** [IvanJosipovic/BlazorApplicationInsights#156]
It would be useful to be able to retrieve the user/session IDs so that I can provide them in error messages. 

It looks like they are stored in cookies by default but I guess that is flexible.

I am happy to add this if you'd accept?

**Comment by tdashworth** [comment]
https://blazorschool.com/tutorial/blazor-wasm/dotnet6/cookie-storage-459520

**Comment by IvanJosipovic** [comment]
Have you checked if there is any code in the ApplicationInsights.JS that performs this function?

**Comment by tdashworth** [comment]
I can't see it in their API.

**Comment by tdashworth** [comment]
Nice! Happy to contribute back and raise a PR?

**Comment by IvanJosipovic** [comment]
A PR would be appreciated :)
