### ISSUE TITLE
Internal exception not visible

### ISSUE THREAD

**Issue by vedion** [IvanJosipovic/BlazorApplicationInsights#173]
Hi,

When logging an exception with an internal exception I can't see the internal exception in Application Insights:

How exception is thrown in Blazor WASM client:
```
var invalidOperationException = new InvalidOperationException("TEST INNER");
throw new NotImplementedException(ExceptionMessage, invalidOperationException);
```

Do you have any plans to improve the logging so the information about the internal exception is also visible in Application Insights?

Best Regards,
Anders Havn

**Comment by IvanJosipovic** [comment]
This issue should be fixed in v3.
