### ISSUE TITLE
Unable to use SetAuthenticatedUserContext method in Blazor Server 

### ISSUE THREAD

**Issue by techierathore** [IvanJosipovic/BlazorApplicationInsights#174]
I am getting following error when I am trying  to use SetAuthenticatedUserContext in Blazor Server application to record logged in user details after successful Azure AD authentication. 
Can anyone **please suggest a solution for this or is Blazor Server not supported ?** 
![Screenshot 2023-02-16 at 12 45 43 PM](https://user-images.githubusercontent.com/7636999/219294456-2ea18a69-d633-421b-acdd-cb3d351d4e7d.png)

**Comment by IvanJosipovic** [comment]
Hey,

This package should work fine with Blazor Sever, I think the issue you are experiance is that you are calling the AI JS function from OnInitializedAsync. This is not supported in Blazor server. JS calls need to be ran on OnAfterRenderAsync.


Please review, https://learn.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-7.0
