### ISSUE TITLE
EasyPrivacy filter blocks js.monitor.azure.com and causes error to be shown

### ISSUE THREAD

**Issue by markdavidoffosit** [IvanJosipovic/BlazorApplicationInsights#192]
Browser extensions that are filtering for privacy scripts (like the EasyPrivacy script that's used by UBlockOrigin) will cause the script that's placed in the index.html file to cause an error:
Microsoft.JSInterop.JSException: Could not find 'appInsights.trackPageView' ('appInsights' was undefined).

I've tracked this down to the:
"https://js.monitor.azure.com/scripts/b/ai.2.min.js", script getting blocked.

Are you able to improve that function to accommodate for the blocking of that script?
Maybe a try-catch that logs error to console rather?

**Comment by IvanJosipovic** [comment]
Hey,

I cant reproduce this, I have tests for this exact scenario. See here, https://github.com/IvanJosipovic/BlazorApplicationInsights/blob/master/src/BlazorApplicationInsights.Tests/UnitTests.cs#L552
