### ISSUE TITLE
Add nonce to script tag for content-security-policy (CSP)

### ISSUE THREAD

**Issue by daver77** [IvanJosipovic/BlazorApplicationInsights#194]
At the moment I need to add "https://*.monitor.azure.com" to my script-src allow-list for my content-security-policy to work which i want to avoid. Has anyone modified the JS to add a nonce attribute to the external JS link? I can add one here to allow the inline script fine.

![image](https://github.com/IvanJosipovic/BlazorApplicationInsights/assets/2369739/880fe2b3-f647-4c53-9606-fc418838e0db)

![image](https://github.com/IvanJosipovic/BlazorApplicationInsights/assets/2369739/a7a47646-9d11-4ece-acd3-d5ff9e125ae3)

**Comment by IvanJosipovic** [comment]
I suggest posting this question here https://github.com/microsoft/ApplicationInsights-JS
