### ISSUE TITLE
Ability to set cloud role name

### ISSUE THREAD

**Issue by CoryKoehler** [IvanJosipovic/BlazorApplicationInsights#20]
For those of us using a single application insights across multiple apps it would be helpful to have the ability to set the cloud role name via `builder.Services.AddBlazorApplicationInsights();` or another method.
I am not sure the best way to do it for this project honestly but it is something I'd love to have :) 

The current way to do this in non blazor wasm projects is to add an ITelemetryInitializer like so
```
public class AppInsightsTelemetryInitializer : ITelemetryInitializer
    {
        public void Initialize(ITelemetry telemetry)
        {
            telemetry.Context.Cloud.RoleName = nameof(OneMarket.Srv.Api);
        }
    }
```

**Comment by IvanJosipovic** [comment]
I have added support for ITelemetryInitializer in version 0.6.0. Please review the readme as there is a new JS file that needs to be loaded.

**Comment by CoryKoehler** [comment]
Thanks so much!
