### ISSUE TITLE
SetEnableAutoRouteTracker Sets the Wrong Property

### ISSUE THREAD

**Issue by tylermurry** [IvanJosipovic/BlazorApplicationInsights#211]
Hello! I am wanting to use this library but with auto route tracking turned `off`.

However, it looks like there may be a bug. In `BlazorAppInsightsConfigBuilder.cs`, the property `ShouldAddLogger` is set instead of `ShouldSetEnableAutoRouteTracking`: 

https://github.com/IvanJosipovic/BlazorApplicationInsights/blob/6c672ea6e30fd95009dfa736e8c3b28cf946518a/src/BlazorApplicationInsights/BlazorApplicationInsightsConfigBuilder.cs#L41-L45

Is this a bug or am I missing something? I would be happy to create a PR for this but this is unfortunately a full blocker fo us using this library at the moment.

Thanks!

**Comment by IvanJosipovic** [comment]
Hey Tyler,

Thanks for this report, it is a bug. Fix is incoming!
