### ISSUE TITLE
how to use with blazor server

### ISSUE THREAD

**Issue by DennyFiguerres** [IvanJosipovic/BlazorApplicationInsights#225]
i have heard that this works with blazor server but how to do that when the install says that i need to add to index.html but blazor server does not have an index.html file in the project.

**Comment by IvanJosipovic** [comment]
Add the code to the equivalent file that contains the index, _Layout.cshtml.

**Comment by DennyFiguerres** [comment]
And in Blazor V7 that page was replaced by /Pages/_Host.cshtml
thanks now i see where to go....
