### ISSUE TITLE
Question: Is ASP.NET Core Hosted model supported for .NET 8?

### ISSUE THREAD

**Issue by mikanygTC** [IvanJosipovic/BlazorApplicationInsights#259]
We have been using this package for some time. Recently we updated an ASP.NET Core hosted Blazor WASM to .NET, but without converting it to Blazor Web App.

I can no longer see samples or instruction for this scenario, so my question: is it no longer supported or can we reuse the same setup as for .NET 6/7?

**Comment by IvanJosipovic** [comment]
It should work, try following the https://github.com/IvanJosipovic/BlazorApplicationInsights#install-on-blazor-webassembly-standalone-app
