### ISSUE TITLE
NuGet Package 3.0.4 Application cannot start

### ISSUE THREAD

**Issue by stephajn** [IvanJosipovic/BlazorApplicationInsights#275]
I upgraded from NuGet package 2.2.0 to 3.0.4 in a Blazor WASM project targeting .NET 8.

I followed the steps in the quick start.
1. I updated my index.html file with the new JavaScript snippet
![image](https://github.com/IvanJosipovic/BlazorApplicationInsights/assets/45795759/77e62893-dec9-441b-950c-1ad06ce11d27)
2. I updated my App.razor file, adding the new Init component at the very top of the file.
![image](https://github.com/IvanJosipovic/BlazorApplicationInsights/assets/45795759/061c5213-4a2b-455a-8ff2-f26ca2b5927f)
3. I updated my Program.cs file, changing the way I instantiated Application Insights
![image](https://github.com/IvanJosipovic/BlazorApplicationInsights/assets/45795759/6244b739-e626-4d1f-b4e0-73b4e9ef3757)

This is the error I get in my console when the application tries to start.  (Note the application never starts, and all I have is just the yellow bar of death)
![image](https://github.com/IvanJosipovic/BlazorApplicationInsights/assets/45795759/ed8d8aab-faf2-421f-b9eb-bade0dbe6dd7)

I tried even adding a line in my csproj to exclude the assembly from being trimmed, although right now I'm not even having the assembly trimmed because I'm running in debug mode.
![image](https://github.com/IvanJosipovic/BlazorApplicationInsights/assets/45795759/163972b8-1b0b-4c60-b737-d4e4261742bc)

I also tried adding this to the top of my Program.cs just to make sure that the Config class didn't get trimmed out
![image](https://github.com/IvanJosipovic/BlazorApplicationInsights/assets/45795759/1e78d223-8053-426f-800b-d365ebdae245)

That did change the error logged in my console, but the end result is still the same. The application will not start, and here's the new error in the browser console.
![image](https://github.com/IvanJosipovic/BlazorApplicationInsights/assets/45795759/d948566d-53a0-4c94-b00c-bb2210ed46f8)

As soon as I rollback all of the changes and go back to version 2.2.0 of the NuGet package, everything works fine.

Updated to add that I also did this because the installation instructions no longer mention having to do it.
![image](https://github.com/IvanJosipovic/BlazorApplicationInsights/assets/45795759/f947db91-7c2f-4204-8b9f-eea1b392221c)

Same result.

Please help? :)

**Comment by IvanJosipovic** [comment]
I'm unfortunately not able to reproduce this.

Can you try to reproduce the error with the sample project?

https://github.com/IvanJosipovic/BlazorApplicationInsights/tree/master/samples/BlazorApplicationInsights.Sample.Wasm

**Comment by amazingalek** [comment]
I had this exact issue. Solved it by deleting the bin and obj folders.

**Comment by HiZackDavid** [comment]
Have you tried to use a connectionString instead of an instrumentationKey to see if it works any differently ? Try adding the connectionString statically first (before getting it from builder.Configuration). If possible, remove the extra elements you added such as commenting the script, the trimmer and DynamicallyAccessedMembers.
