### ISSUE TITLE
Missing "sampleRate" property on ITelemetryItem

### ISSUE THREAD

**Issue by eduard-tapkey** [IvanJosipovic/BlazorApplicationInsights#286]
Hi,

I would like to enforce certain messages to be sent to AI despite adaptive sampling.
To my current knowledge, I need to write `TelemetryInitializer `that in those certain conditions enforces sample rate on client to 100%. 
From my research it seems that the property to be used is on `envelope ` when calling `addTelemetryInitializer`. 
I'm not able to find this property on `ITelemetryItem `here and writing it to Tags seems not to work. 
Is there anyway to enforce this or is this missing in the implementation?

**Comment by IvanJosipovic** [comment]
This library doesn't support the full Telemetry Initializer capabilities. This is due to the fact that JSInterop is async and the Telemetry Initializer callback is synchronous.

You can do this manually using some JS.
