### ISSUE TITLE
Configure minimum LogLevel

### ISSUE THREAD

**Issue by tariqalsoahmed** [IvanJosipovic/BlazorApplicationInsights#289]
I'd like to only log Warnings and Errors.

Couldn't find a way to do this with the current API?

**Comment by tariqalsoahmed** [comment]
Hi @IvanJosipovic I've coded a fix for this, by configuring ApplicationInsightsLoggerOptions.MinLogLevel

Please let me know if you'd like me to push the code on a new branch

**Comment by IvanJosipovic** [comment]
Thank you, it has been released in 3.1.0.
