### ISSUE TITLE
Exception when starting in debug

### ISSUE THREAD

**Issue by mark-at-tusksoft** [IvanJosipovic/BlazorApplicationInsights#5]
My implementation is almost verbatim for the example. Only major difference is that my App.razor is wrapped in a `<CascadingAuthenticationState>` component and the `<ApplicationInsightsComponent>` is outside of it.
`Microsoft.JSInterop.JSException: Could not find 'appInsights' in 'window'.`

If I reload the page, the error goes away.

**Comment by IvanJosipovic** [comment]
The error is saying that the JS Interop can't find the appInsights JavaScript object.
Have you added the JS snippet to the index.html?

Example, 
https://github.com/IvanJosipovic/BlazorApplicationInsights/blob/df1ff8a6e13b8508282cf31c69433efd9cb14a11/src/BlazorApplicationInsights.Sample/wwwroot/index.html#L9

**Comment by mark-at-tusksoft** [comment]
Yes, as mentioned, it does work if I reload the page.

**Comment by IvanJosipovic** [comment]
I just checked one of my work projects which uses auth. I am not seeing the same issue that you're experiencing.

Here is the App.razor
```
<CascadingAuthenticationState>
    <CascadingBlazoredModal>
        <Router AppAssembly="@typeof(Program).Assembly">
            <Found Context="routeData">
                <AuthorizeRouteView RouteData="@routeData" DefaultLayout="@typeof(MainLayout)">
                    <NotAuthorized>
                        @if (!context.User.Identity.IsAuthenticated)
                        {
                            <RedirectToLogin />
                        }
                        else
                        {
                            <p>You are not authorized to access this resource.</p>
                        }
                    </NotAuthorized>
                </AuthorizeRouteView>
            </Found>
            <NotFound>
                <LayoutView Layout="@typeof(MainLayout)">
                    <p>Sorry, there's nothing at this address.</p>
                </LayoutView>
            </NotFound>
        </Router>
    </CascadingBlazoredModal>
</CascadingAuthenticationState>
<ApplicationInsightsComponent />
```

I wonder if this is a timing issue. Can you please edit your JS snippet and set the ld parameter to -1.

```
ld: -1, // Defines the load delay (in ms) before attempting to load the sdk. -1 = block page load and add to head. (default) = 0ms 
```

**Comment by IvanJosipovic** [comment]
I had this issue happen to me, I tested with ld = -1 and it hasn't reoccurred. I have updated the installation guidance in the readme. Let me know if you see this issue again.
