### ISSUE TITLE
Receiving Unhandled Exception when using BlazorApplicationInsights with Azure AD SSO Integration on login callback

### ISSUE THREAD

**Issue by robertlamberson** [IvanJosipovic/BlazorApplicationInsights#51]
I have a small application using .Net 5 and Blazor Webassembly and using Azure AD SSO for authentication.   When the login authentication completes and issues the callback to the app it is generating the following exception.   It appears that a response from the login callback is not being handled in the BAI well.   The authentication process is still successful but generates a client messages that needs to be dismissed, so this is not a blocking issue but is a distraction in the user flow.   Also the authentication process did not generate this unhandled message prior to adding in the BAI client side logging.

I am attaching the logs from the client side and an image from the developer tools console.

[unhandled_exception.log](https://github.com/IvanJosipovic/BlazorApplicationInsights/files/5837459/unhandled_exception.log)

![image](https://user-images.githubusercontent.com/16200609/105069077-24b5bc80-5a47-11eb-83e1-1c49c483ae01.png)

Any thoughts on resolving this?

**Comment by IvanJosipovic** [comment]
Hey,

I'm using this library in a .Net 5 Blazor wasm app with no issues. I'm thinking that your username is null or you are sending some illegal characters (spaces or ,;=|).

Can you please try to updated your Authentication.razor to look like this?


```
@page "/authentication/{action}"

<RemoteAuthenticatorView Action="@Action" OnLogInSucceeded="OnLogInSucceeded" OnLogOutSucceeded="OnLogOutSucceeded">
</RemoteAuthenticatorView>

@code{
    [Parameter] public string Action { get; set; }
    [CascadingParameter] public Task<AuthenticationState> AuthenticationState { get; set; }   
    [Inject] private IApplicationInsights AppInsights { get; set; }

    public async Task OnLogInSucceeded()
    {
        var user = (await AuthenticationState).User;
        var newName = user.Identity.Name;

        if(!string.IsNullOrEmpty(newName))
        {
            // Replace illegal characters
            newName = new System.Text.RegularExpressions.Regex("[,;=| ]+").Replace(newName, "_");
        
            await AppInsights.SetAuthenticatedUserContext(newName, null, true);
        }
    }
    
    public async Task OnLogOutSucceeded()
    {
        await AppInsights.ClearAuthenticatedUserContext();
    }
}

```

**Comment by robertlamberson** [comment]
@IvanJosipovic that was it, I had wrapped the OnLogInSucceeded in a try catch so I didn't inspect closely what it was pushing back into the User Name context!! 

Thanks for the quick response
