### ISSUE TITLE
Missing Name Field on RemoteDependency

### ISSUE THREAD

**Issue by juanidamato** [IvanJosipovic/BlazorApplicationInsights#57]
Hi,
I'm getting a bad request (400 error code) response from applications insights servers when I try to add a  RemoteDependency. 

It is reporting this error:
Field 'name' on type 'RemoteDependencyData' is required but missing or empty. Expected: string, Actual: undefined"}],"appId":"087e40d6-a306-4eeb-9c79-2b3115ce0440"

TrackTrace and PageviewData are working well.

Regards,
Juan

**Comment by IvanJosipovic** [comment]
Hey, do you mind posing the code that reproduces this issue?

**Comment by juanidamato** [comment]
public async
Task<List<SharedUtils.Models.ViewModels.AdminPeopleViewModel>>
GetAll(IApplicationInsights AppInsights)
        {
            int status;
            HttpClient oneHttp = new HttpClient();
            List<SharedUtils.Models.ViewModels.AdminPeopleViewModel>
ReturnData = null;



oneHttp.DefaultRequestHeaders.Add("Access-Control-Allow-Headers",
"request-context");

            using(var  ajaxR = await oneHttp.GetAsync("
https://localhost:44335/api/people"))
            {
                var content = await ajaxR.Content.ReadAsStringAsync();
                status = (int)ajaxR.StatusCode;
                if (status != 200)
                {
                    //todo
                    return null;
                }
                ReturnData = new
List<SharedUtils.Models.ViewModels.AdminPeopleViewModel>();

                ReturnData =
Newtonsoft.Json.JsonConvert.DeserializeObject<List<SharedUtils.Models.ViewModels.AdminPeopleViewModel>>(content);

                string data = "";
                if (ajaxR.Headers.TryGetValues("request-context", out
IEnumerable<string> headercontext))
                {
                    data = headercontext.FirstOrDefault();
                }
                if (!string.IsNullOrWhiteSpace(data))
                {
                    Dictionary<string, object> props = new
Dictionary<string, object>();
                    props.Add("name", "xxx");
                    await AppInsights.TrackDependencyData(data,
200,null,true,null,50,null,props);  * //THIS LINE POST THE DATA AND THE
RESULT IS A 400 CODE WITH THE ERROR MESSAGE OF name field is required*
                   // await AppInsights.Flush();
                }
            }

            return ReturnData;
        }

**Comment by IvanJosipovic** [comment]
Thanks, I'll have a look at this in the evening.

**Comment by juanidamato** [comment]
Hi,
This is the summary of my chrome network data


*General*
Request URL: https://dc.services.visualstudio.com/v2/track
Request Method: POST
Status Code: 400
Remote Address: 40.71.13.170:443
Referrer Policy: no-referrer-when-downgrade


*Response Headers*
access-control-allow-headers: Origin, X-Requested-With, Content-Name,
Content-Type, Accept, Sdk-Context
access-control-allow-origin: *
access-control-max-age: 3600
content-length: 255
content-type: application/json; charset=utf-8
date: Wed, 10 Feb 2021 19:26:20 GMT
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-ms-session-id: EAC1BCCD-6C88-43AB-8619-5B356A149A74

*Request Headers*
:authority: dc.services.visualstudio.com
:method: POST
:path: /v2/track
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: es-ES,es;q=0.9
content-length: 737
content-type: application/json
origin: https://localhost:44345
referer: https://localhost:44345/people
sdk-context: appId
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
(KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36

*Payload:*
[{time: "2021-02-10T19:26:05.577Z", iKey:
"f0e1d67f-b886-4b0a-8b36-99ffd624ec4d",…}]
0: {time: "2021-02-10T19:26:05.577Z", iKey:
"f0e1d67f-b886-4b0a-8b36-99ffd624ec4d",…}
data: {baseType: "RemoteDependencyData",…}
baseData: {id: "appId=cid-v1:087e40d6-a306-4eeb-9c79-2b3115ce0440", ver: 2,
resultCode: "200",…}
duration: "00:00:00.050"
id: "appId=cid-v1:087e40d6-a306-4eeb-9c79-2b3115ce0440"
measurements: {}
properties: {name: "xxx"}
name: "xxx"
resultCode: "200"
success: true
type: "Ajax"
ver: 2
baseType: "RemoteDependencyData"
iKey: "f0e1d67f-b886-4b0a-8b36-99ffd624ec4d"
name:
"Microsoft.ApplicationInsights.f0e1d67fb8864b0a8b3699ffd624ec4d.RemoteDependency"
tags: {ai.user.id: "kUHf/PKTuSU0v/3S2Hlrep", ai.session.id:
"/XtIDHPsYclDzLio54xjPL",…}
ai.cloud.role: "SPA3"
ai.cloud.roleInstance: "Blazor Wasm3"
ai.device.id: "browser"
ai.device.type: "Browser"
ai.internal.sdkVersion: "javascript:2.5.11"
ai.operation.id: "10597383a1014a4c8e9fff1cf0aee57b"
ai.operation.name: "/"
ai.session.id: "/XtIDHPsYclDzLio54xjPL"
ai.user.id: "kUHf/PKTuSU0v/3S2Hlrep"
time: "2021-02-10T19:26:05.577Z"


*RESPONSE BODY (THE ERROR)*
{"itemsReceived":1,"itemsAccepted":0,"errors":[{"index":0,"statusCode":400,"message":"109:
Field 'name' on type 'RemoteDependencyData' is required but missing or
empty. Expected: string, Actual:
undefined"}],"appId":"087e40d6-a306-4eeb-9c79-2b3115ce0440"}

**Comment by IvanJosipovic** [comment]
This issue is fixed in 0.8.0. The [Documentation](https://github.com/microsoft/ApplicationInsights-JS/blob/master/API-reference.md#trackdependencydata) was incorrect, I had to look at the code to implement this properly 👎.

Thanks for the reporst
