### ISSUE TITLE
Correlation with api requests

### ISSUE THREAD

**Issue by rsloggett-prmaconsulting** [IvanJosipovic/BlazorApplicationInsights#62]
Big thankyou for this project - up and running really quickly and working great.

One thing I would like to figure out is how to correlate api requests made through an HttpClient instance with the back end telemetry. I'm assuming nothing is baked in for this just yet (not seeing any headers on outbound requests) but wonder if you had any thoughts on what would be necessary to get this working before I roll my sleeves up :)

**Comment by IvanJosipovic** [comment]
It appears there are some docs for this, https://docs.microsoft.com/en-us/azure/azure-monitor/app/javascript#enable-correlation

Let me know if these solve your issue.

**Comment by rsloggett-prmaconsulting** [comment]
Thank you so much for pointer and apologies for missing it first time through the application insight js docs. Can confirm that this works great - adding the required headers to requests from Blazor so they are correlating correctly with the client application insights entry. It all adds up to a full end to end timeline from page load through to api requests which is great from a diagnostic point of view.
