### ISSUE TITLE
Load instrumentation key from appsettings or code

### ISSUE THREAD

**Issue by rsloggett-prmaconsulting** [IvanJosipovic/BlazorApplicationInsights#63]
Do you have any plans to add support for loading the instrumentation key from appsettings, or from the app startup code? Looking at ways to avoid having to create copies of index.html for different deployment environments and interested if you had considered this and / or had any ideas about how best to tackle it?

**Comment by rsloggett-prmaconsulting** [comment]
It seems as though the ideal would be to be able to optionally set the key in the call to services.AddBlazorApplicationInsights - that way you could chose the approach best suited - either replace in CI/CD deployment (which I agree is probably ideal) or set in code during startup. Our scenario is multi tenant where the key is not known until the app is starting up and I'm sure there are other scenarios where setting the key from code would be really useful.

**Comment by Mfolmer** [comment]
Out of curiosity do you mind sharing some details on how you replaced the key in your pipeline?

I have an Azure App Service for my application where I configure settings etc. however I haven't managed to find a way to replace to instrumentation key in the JavaScript in head in index.html. 
Maybe you are using a complete different setup, however any input are greatly appreciated.

**Comment by rsloggett-prmaconsulting** [comment]
For the scenario where the application insights key is known at deploy time, we ended up breaking out the script block into a script file then in our repo we include a local dev script file (applicationinsights.js) and a copy for each environment (e.g. applicationinsights.DEV.js). Then in the Deploy to App Service task we set a post deploy script that deletes the local dev applicationinsights.js file and copies over the appropriate one for the environment we are deploying to (e.g. applicationinsights.QA.js -> applicationinsights.js). 

You could use the same idea for index.html but in our scenario everything else in there was identical and we didn't want to have to keep all the copies in sync as changes were inevitably made to index.html.

**Comment by IvanJosipovic** [comment]
This feature has been added in 1.1.0. https://github.com/IvanJosipovic/BlazorApplicationInsights#set-instrumentation-key
