### ISSUE TITLE
WASM or Server Side?

### ISSUE THREAD

**Issue by Liero** [IvanJosipovic/BlazorApplicationInsights#66]
Is this package for Blazor WASM or ServerSide or both? Please mention in explicitly in readme.md

**Comment by IvanJosipovic** [comment]
I am only testing this on WASM. However, it should work on Server as well.

**Comment by Liero** [comment]
I've inspected the code more carefully and it's not very suitable for server side Blazor. It requires to configure Appinsights in javascript and then invokes javascript to do the logging although it could do the logging directly on server with TelemetryClient.

**Comment by IvanJosipovic** [comment]
Just a FYI, logging is only enabled on Blazor WASM, see here https://github.com/IvanJosipovic/BlazorApplicationInsights/blob/df9cf754074baa924c2239cd8771593647e857ce/src/BlazorApplicationInsights/IServiceCollectionExtensions.cs#L21

**Comment by jostFT** [comment]
Would it be possible to explicitly state that this is not for server side in the readme? :)
Just incase someone doesn't think of checking the issues :)

**Comment by IvanJosipovic** [comment]
> Just incase someone doesn't think of checking the issues :)

I'm not sure that's fully the case. Its just the logger that is not supported as we don't want to ship logs to the browser. Is there something else that isn't working?

**Comment by jostFT** [comment]
> > Just incase someone doesn't think of checking the issues :)
> 
> I'm not sure that's fully the case. Its just the logger that is not supported as we don't want to ship logs to the browser. Is there something else that isn't working?

Hey, my apologies. We tested it on server side, and it works perfectly fine as far as we can tell :)
If we encounter any issues we'll be sure to create an issue on it at a later date. But from our testing, it seems to be working fine :)
