### ISSUE TITLE
SetAuthenticatedUserContext calls wrong api function

### ISSUE THREAD

**Issue by michaelmarcuccio** [IvanJosipovic/BlazorApplicationInsights#9]
I believe the IApplicationInsights.SetAuthenticatedUserContext method calls the ClearAuthenticatedUserContext script function instead of the correct function. I am not able to set authenticated user context.

**Comment by IvanJosipovic** [comment]
Thanks for reporting this issue. It has been fixed in Release [0.3.0](https://github.com/IvanJosipovic/BlazorApplicationInsights/releases/tag/v0.3.0).

**Comment by michaelmarcuccio** [comment]
Thanks for this quick fix. I am not sure if it is just me not knowing how it works or not, but my App Insights logs are still not showing the userId set by the function. 
`await AppInsights.SetAuthenticatedUserContext($"{userId}");`

**Comment by IvanJosipovic** [comment]
I found a bug in the JSInterop and fixed in Release [0.4.0](https://github.com/IvanJosipovic/BlazorApplicationInsights/releases/tag/v0.4.0).
I also documented how to set the username in the [Readme](https://github.com/IvanJosipovic/BlazorApplicationInsights#set-user-name)
